<?xml version="1.0" encoding="UTF-8"?><testrun name="AccidentReportTestCase1" project="GUIAapp" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="junitTest.AccidentReportTestCase1" time="0.002">
    <testcase name="testAccidentReportStringStringStringLocalDateTimeString" classname="junitTest.AccidentReportTestCase1" time="0.002">
      <failure>
        <expected>VIN11111</expected>
        <actual>VIN12345</actual>
        org.junit.ComparisonFailure: expected:&lt;VIN1[1111]&gt; but was:&lt;VIN1[2345]&gt;
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at junitTest.AccidentReportTestCase1.testAccidentReportStringStringStringLocalDateTimeString(AccidentReportTestCase1.java:22)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)


      </failure>
    </testcase>
    <testcase name="testGetVin1" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
    <testcase name="testGetVin2" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
    <testcase name="testGetAccidentLocation" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
    <testcase name="testGetDescription" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
    <testcase name="testGenerateAccidentReport" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
    <testcase name="testSendReportToInsurance" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
    <testcase name="testGetAccidentTime" classname="junitTest.AccidentReportTestCase1" time="0.0"/>
  </testsuite>
</testrun>
